// LLD configuration: View -> Groups -> Sub-groups -> Equipments.
// CamelCase throughout — there is no real upstream payload to mirror yet
// (the service runs on a mock, see NxLldService).

// ---------------------------------------------------------------- lookups
// Every dropdown/checklist value, delivered by ONE call (getLookups()) —
// assets/mock-api/lld-lookups.json for now. Lookup ids are strings; record
// ids (below) are server-assigned numbers.
export interface LldLookups {
  subsurfaces: LldSubsurface[];
  subGroupTypes: LldSubGroupType[];
  equipments: LldOption[];
}

export interface LldOption {
  id: string;
  name: string;
}

// The View popup's Subsurface dropdown; picking one swaps the Stations
// multi-select to that subsurface's own stations (one-to-many).
export interface LldSubsurface extends LldOption {
  stations: LldOption[];
}

// The Sub-group popup's Type dropdown; picking one loads its template
// versions into the Template dropdown.
export interface LldSubGroupType extends LldOption {
  templates: LldTemplate[];
}

export interface LldTemplate extends LldOption {
  version: string;
}

// ---------------------------------------------------------------- records
// `id` is assigned by the SERVER — absent on a new record's save payload,
// present on an edit's (same save URL either way). Never generated by the UI.

// Sent to the server as the number. Deleted is a soft delete: set only by
// the Delete button (NxLldService.deleteView) — the record stays in the
// database but is never listed again.
export enum LldViewStatus {
  Private = 1,
  Public = 2,
  Deleted = 3
}

// What the View popup's Status dropdown offers — Deleted isn't pickable.
export const LLD_VIEW_STATUS_OPTIONS: { value: LldViewStatus; label: string }[] = [
  { value: LldViewStatus.Private, label: "Private" },
  { value: LldViewStatus.Public, label: "Public" }
];

export interface LldView {
  id?: number | null;
  name: string;
  subsurfaceId: string;
  // Selected stations — all belong to subsurfaceId's own `stations`.
  stationIds: string[];
  status: LldViewStatus;
  description: string;
}

export interface LldGroup {
  id?: number | null;
  viewId: number;
  name: string;
}

// One sub-group = ONE type + ONE template for every equipment in it —
// mixed templates aren't representable, by design.
export interface LldSubGroup {
  id?: number | null;
  groupId: number;
  name: string;
  typeId: string;
  templateId: string;
  // At least one; no duplicates.
  equipmentIds: string[];
}

// What getGroups(viewId) returns: each group with its own sub-groups, so
// the grouped layout renders from a single call.
export interface LldGroupWithSubGroups extends LldGroup {
  subGroups: LldSubGroup[];
}
